var GAME_LEVELS = [
   // Level 1
   ["                                                                                ",
	"                                                                                ",
	"  xxx                                                                     xxxx  ",
	"  x                                                                       x!!x  ",
	"  x                        o o                                            xvxx  ",
	"  x                                                                g         x  ",
	"  x                       xxxxx                                 xxxxx        x  ",
	"  x                                                       xx                 x  ",
	"  x                                                                          x  ",
	"  x                                        xxxx                              x  ",
	"  x                                                 xx                       x  ",
	"  x                                                                          x  ",
	"  x                                 o  o                                     x  ",
	"  x                     o                                                    x  ",
	"  x                                xxxxxx                                  o x  ",
	"  x                     o                                                    x  ",
	"  x  @                                                                       x  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            xxxxxxxxxxxxxxxxxxx  ",
	"                              x                            x                    ",
	"                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
	"                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
	"                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
	"                                                                                ",
	"                                                                                "],
   
   // Level 2
   ["                                      x!!x                   xxxxxxxxxxxxxxxxx             x!!!!!!!!!!!!!!!!!!!x  ",
	"                                      x!!x                   x               x             xxxvxxxxxvxxxxvxxvx!x  ",
	"                                      x!!xxxxxxxxxx          x               x                               x!x  ",
	"                                      xx!!!!!!!!!!xx         x               x                               x!x  ",
	"                                       xxxxxxxxxx!!x         x                                               x!x  ",
	"                                                xx!x         x    o     o                   o     o     o   xx!x  ",
	"                                                 x!x         x                             xxxxxxxxxxxxxxxxxx!!x  ",
	"                                                 xvx         x   xxx | xxx                 !!!!!!!!!!!!!!!!!!!xx  ",
	"                                                             x!!!!!!!!!!!!!!xx            x!xxxxxxxxxxxxxxxxxxx   ",
	"                                                             x!!!!!!!!!!!!!!xxxx           v                      ",
	"                              o                              xxxxxxxxxxxxxxxxx                                    ",
	"                                               x     x       xxaaxxxxxxxxxxxxx                                    ",
	"                                               x     x                    xxxx                                    ",
	"     a                                         x     x                    xx                                      ",
	"                                               x     x                    xx          xxxx                        ",
	"                                             xxxx    x                    xx                  xxxxxx              ",
	"                                               x     x                    xx                                      ",
	"                                               x     x                    xx                             o        ",
	"                                  o            x     x                    xx                           xxxxxx     ",
	"                   xxxxx                       x    xx   =    =      x    xx                                      ",
	"     @             x   x        xxxxx          x     xxxxxxxxxxxxxxxxx    xx                                   x  ",
	"    xxx            x   x                       x     x                    xx                                      ",
	"    x x            x   x                       x     x                    xx                               o      ",
	"!!!!x x!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!xx    x!!!!!!!!!!          xx    xxxxxxxxxxx               xxxx    ",
	"!!!!x x!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!x     x!!!!!!!xx!          xx                                      ",
	"!!!!x x!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!x    xx!!!!!!xx !      o   xx                                      ",
	"!!!!x x!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!xx    x!!!!!xx  !    xxxxx xx                xxxx                  ",
	"!!!!x x!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!x    gx!!!!xx   !          xx                                      ",
	"!!!!x x!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!xx!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!x x!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
   // Level 3
   ["                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                    o                       x                                                 ",
	"                                                            x                                                 ",
	"                                    x                       x                                                 ",
	"                                    x                       x                                                 ",
	"                                    x                       x                                                 ",
	"                                    x                       x                                                 ",
	"                                    x                       x                                                 ",
	"                                  xxxxx                     x         !!!  xxx                                ",
	"                                  x                         x         !x!              xxx                    ",
	"                                  x                         x          x              x!!!x                   ",
	"                                 xx xxxx                    x   oooo   x               xxx                    ",
	"                                 x     x                    x          x                                      ",
	"                                 x     x                    xxxxxxxxxxxx                                      ",
	"                               xxxxx  xxxxxxxxxxxxx   x     xx                                                ",
	"                               x          x           xxxxxxxx                                                ",
	"                               x          x      =    x                             xxx                       ",
	"                               x      xxxxx           x                            x!!!x a                    ",
	"                               x          x                                         xxx                       ",
	"                               x          x                        xxx                                        ",
	"                               x          x           x           x!!!x                                       ",
	"                               x          x      =    x     o      xxx       xxx                      xx      ",
	"                               xxx  xxxxxxx           x                     x!!!x        o                    ",
	"                               x          x           x   xxxx               xxv        xxx                   ",
	"                               x          x           x              x                 x!!!x                  ",
	"                              xxxxxxxx   xxx     o o  x!!!!!!!!!!!!!!x                  xxv                   ",
	"                              x           xx          x!!!!!!!!!!!!!!x                                      xx",
	"                              x           xx   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
	"                              x           xx                                         xxx                      ",
	"  xxx                         x         xxxx                                        x!!!x                xxx  ",
	"  x x                         x           xx                                         xxx                 x x  ",
	"  x                           x           xx                             xxxxx                             x  ",
	"  x                           x           xx                             x!!!x                             x  ",
	"  x                           xx          xx                             x!!!x                             x  ",
	"  x                 o                     xx        |xxxx|  |xxxx|  xxxxxxxx!x                             x  ",
	"  x                xxx             o o    xx  o                      xxxxxx !      xxx           g         x  ",
	"  x               xxxxx       xx          xx xxx                      xxxxx !     x!!!x          x         x  ",
	"  x              xxxxxxx      xx   xxx    xx                           xx x !      xxx           x         x  ",
	"  x             xxxxxxxxx     xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!xx xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
	"  x      @     xxxxxxxxxxx    x           xx!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"                                                                                                              ",
	"                                                                                                              "],
	
   ["                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                                    o           ",
	"                                  o           o         o                       ",
	"               o      o                                          o              ",
	"                  o                o            o      o                        ",
	"                   x   x      x       x    x                                    ",
	"                    x x      x x      x    x            o           o           ",
	"                     x      x   x     x    x     o                              ",
	"            o  o     x      x   x     x    x                  o                 ",
	"                     x       x x      x  @ x    o        o                      ",
	"                     x   o    x    o   xxxx           o                         ",
	"                                                                                ",
	"                o         x      x     xxxxxxx      xx    x                     ",
	"                          x   o  x        x         x x   x           o         ",
	"           o         o    x      x    o   x     o   x  x  x    o                ",
	"                          x  xx  x        x         x   x x                     ",
	"                          x x  x x        x         x    xx                     ",
	"                       o  xx    xx     xxxxxxx      x     x                     ",
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
	
   ["                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                                    g           ",
	"                                  o           o         o                       ",
	"               o      o                                          o              ",
	"                  g                o            g      o                        ",
	"                   x   x      x       x    x                                    ",
	"                    x x      x x      x    x            o           o           ",
	"                     x      x   x     x    x     o                              ",
	"            o  g     x      x   x     x    x                  g                 ",
	"                     x       x x      x  @ x    g        o                      ",
	"                     x   o    x    o   xxxx           o                         ",
	"                                                                                ",
	"                o         x      x     xxxxxxx      xx    x                     ",
	"                          x   o  x        x         x x   x           o         ",
	"           o         g    x      x    g   x     o   x  x  x    o                ",
	"                          x  xx  x        x         x   x x                     ",
	"                          x x  x x        x         x    xx                     ",
	"                       o  xx    xx     xxxxxxx      x     x                     ",
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
	
];

if (typeof module != "undefined" && module.exports) {
	module.exports = GAME_LEVELS;
}
