var GAME_LEVELS = [
   // Level 1
   ["                                                                                ",
	"                                                                                ",
	"  xxx                                                                      xxx  ",
	"  x                                                                          x  ",
	"  x                                                                          x  ",
	"  x                                                                g         x  ",
	"  x                                                               xxx        x  ",
	"  x                                                xx     xx     xx!xx       x  ",
	"  x                              o o         xx                  x!!!x       x  ",
	"  x                                                              xx!xx       x  ",
	"  x                             xxxxx                             xvx        x  ",
	"  x                                                                          x  ",
	"  x                                       o o                                x  ",
	"  x                     o                                                    x  ",
	"  x                                      xxxxx                             o x  ",
	"  x          xxxx       o                                                    x  ",
	"  x  @       x  x                                                            x  ",
	"  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxx                 xxxxxxxxxxxxxxxxxxx  ",
	"                              x   x      x                 x                    ",
	"                              x!!!x      x!!!!!!!!!!!!!!!!!x                    ",
	"                              x!!!x      x!!!!!!!!!!!!!!!!!x                    ",
	"                              xxxxx      xxxxxxxxxxxxxxxxxxx                    ",
	"                                                                                ",
	"                                                                                "],
   
   // Level 2
   ["                                      x!!x                   xxxxxxxxxxxxxxxxx                             x!!!x  ",
	"                                      x!!x                   x               x                              vx!x  ",
	"                                      x!!xxxxxxxxxx          x               x                               x!x  ",
	"                                      xx!!!!!!!!!!xx         x               x                               x!x  ",
	"                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
	"                                                xx!x         x    o     o                                   xx!x  ",
	"                                                 x!x         x                             xxxxxxxxxxxxxxxxxx!!x  ",
	"                                                 xvx         x   xxx | xxx                 !!!!!!!!!!!!!!!!!!!xx  ",
	"                                                             x!!!!!!!!!!!!!!xx            x!xxxxxxxxxxxxxxxxxxx   ",
	"                                                             x!!!!!!!!!!!!!!xxxx           v                      ",
	"                              o                              xxxxxxxxxxxxxxxxx                                    ",
	"                                               x     x       xxaaxxxxxxxxxxxxx                                    ",
	"                                               x     x                    xxxx                                    ",
	"     a                                         x     x                    xx                                      ",
	"                                               x     x                    xx          xxxx                        ",
	"                                             xxxx    x                    xx                  xxxxxx              ",
	"                                               x     x     o   o          xx                                      ",
	"               xxxxxxx                         x     x   x   =    x       xx                             o        ",
	"              xx     xx           o            x     x   xxxxxxxxxx       xx                           xxxxxx     ",
	"             xx       xx                       x    xx                    xx                                      ",
	"     @       x         x        xxxxx          x     x                    xx                                      ",
	"    xxx      x         x                       x     x                    xx                                      ",
	"    x x      x         x                       x     x                    xx                                      ",
	"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xx    x!!!!!!!!!!          xx    xxxxxxxxxxx                       ",
	"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!x     x!!!!!!!xx!          xx                                      ",
	"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xg   xx!!!!!!xx !          xx                                      ",
	"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!x     x!!!!!xx  !          xx                                      ",
	"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!xx   !          xx                                      ",
	"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
   // Level 3
   ["                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                                            x                                                 ",
	"                                        o                   x                                                 ",
	"                                                            x                                                 ",
	"                                        x                   x                                                 ",
	"                                        x                   x                                                 ",
	"                                        x                   x                                                 ",
	"                                        x                   x                                                 ",
	"                                       xxx                  x                                                 ",
	"                                       x x                  x         !!!  xxx                                ",
	"                                       x x                  x         !x!                                     ",
	"                                     xxx xxx                x          x                                      ",
	"                                      x   x                 x   oooo   x       xxx                            ",
	"                                      x   x                 x          x      x!!!x                           ",
	"                                      x   x                 xxxxxxxxxxxx       xxx                            ",
	"                                   xxxx   xxxxxxxxx   x     xx                                                ",
	"                                      x   xxxxxxxxx   xxxxxxxx                                                ",
	"                                      x   x           x                             xxx                       ",
	"                                    o x   x           x                            x!!!x a                    ",
	"                                 xxxxxx   x    =      x                             xxx                       ",
	"                                      x   x           x            xxx                                        ",
	"                                      x   x           x           x!!!x                                       ",
	"                                      x   x      =    x     o      xxx       xxx                      xx      ",
	"                               xxxxxxxx   xx          x                     x!!!x        o                    ",
	"                                      x   x           x    xxx               xxv        xxx                   ",
	"                                      x   x           x              x                 x!!!x                  ",
	"                             xxxxxxxxxxxxxxx     o o  x!!!!!!!!!!!!!!x                  xxv                   ",
	"                             x            xx          x!!!!!!!!!!!!!!x                                      xx",
	"                             x            xx   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
	"                             xx           xx                                         xxx                      ",
	"  xxx                         x     x     xx                                        x!!!x                xxx  ",
	"  x x                         x    xxx    xx                                         xxx                 x x  ",
	"  x                       xxxxx    xxx    xx                             xxxxx                             x  ",
	"  x                           x           xx                             x!!!x                             x  ",
	"  x                           xx          xx                             x!!!x                             x  ",
	"  x                 o                     xx        |xxxx|  |xxxx|  xxxxxxxxxx                         xxxxx  ",
	"  x                xxx             o o    xx  o                      xxxxxx        xxx           g         x  ",
	"  x               xxxxx       xx          xx xxx                      xxxxx       x!!!x          x         x  ",
	"  x              xxxxxxx      xx   xxx    xx                           xx x        xxx          xxx        x  ",
	"  x             xxxxxxxxx     xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!xx xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
	"  x      @     xxxxxxxxxxx    x           xx!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"                                                                                                              ",
	"                                                                                                              "],
	
   ["                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                                    o           ",
	"                                  o           o         o                       ",
	"               o      o                                          o              ",
	"                  o                o            o      o                        ",
	"                   x   x      x       x    x                                    ",
	"                    x x      x x      x    x            o           o           ",
	"                     x      x   x     x    x     o                              ",
	"            o  o     x      x   x     x    x                  o                 ",
	"                     x       x x      x  @ x    o        o                      ",
	"                     x   o    x    o   xxxx           o                         ",
	"                                                                                ",
	"                o         x      x     xxxxxxx      xx    x                     ",
	"                          x   o  x        x         x x   x           o         ",
	"           o         o    x      x    o   x     o   x  x  x    o                ",
	"                          x  xx  x        x         x   x x                     ",
	"                          x x  x x        x         x    xx                     ",
	"                       o  xx    xx     xxxxxxx      x     x                     ",
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
	
   ["                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                                    g           ",
	"                                  o           o         o                       ",
	"               o      o                                          o              ",
	"                  g                o            g      o                        ",
	"                   x   x      x       x    x                                    ",
	"                    x x      x x      x    x            o           o           ",
	"                     x      x   x     x    x     o                              ",
	"            o  g     x      x   x     x    x                  g                 ",
	"                     x       x x      x  @ x    g        o                      ",
	"                     x   o    x    o   xxxx           o                         ",
	"                                                                                ",
	"                o         x      x     xxxxxxx      xx    x                     ",
	"                          x   o  x        x         x x   x           o         ",
	"           o         g    x      x    g   x     o   x  x  x    o                ",
	"                          x  xx  x        x         x   x x                     ",
	"                          x x  x x        x         x    xx                     ",
	"                       o  xx    xx     xxxxxxx      x     x                     ",
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
	
];

if (typeof module != "undefined" && module.exports) {
	module.exports = GAME_LEVELS;
}
